### ISSUE TITLE
QUESTION: FITTING IMPROVEMENT

### ISSUE THREAD

**Issue by stmiguel** [e-champenois/CPBASEX#5]
Dear Elio,

I'm trying to abel-inverse some images of xenon using your pBASEX code. However, somehow the fit trace does not reproduce fine features that are relevant for finding the beta parameters. I was wondering if you could give me some advice for improving my fit. 

Attached you find an example of the problem I'm having. In case it's useful, xenon was ionized by 266 nm pulses, implying that we have roughly a 3-photon absorption process.

I'm looking forward to your reply! Thank you!

![pbasex-champenois](https://user-images.githubusercontent.com/27637366/40658080-50bfd0c8-634a-11e8-9b24-ddde9148a3fb.png)

**Comment by e-champenois** [comment]
Hi,
Correct me if I'm wrong, but I believe the issue here is that you are using
the default config of l_max = 4 when running the save_gData script. This
gives polar contributions up to P_4(cos theta). However, with 3-photon
ionization, you might expect contributions up to P_6(cos theta).

In fact, I have taken very similar data during my PhD work for calibration
of our VMI, ionizing Xenon with a femtosecond pulse at 260nm. It looks very
similar to your data visually (see attached), and I measure almost
negligible intensity in P_4(cos theta), which could explain why you don't
see it in your fit. The small bump that you are looking for does show up
and comes mainly from P_6(cos theta), since using l_max = 6 or l_max = 8
gives very similar results.

Let me know if you have any other issues, questions, or even comments about
the code!

Thanks, Elio

**Comment by e-champenois** [comment]
![calib_xenon](https://user-images.githubusercontent.com/8816959/40677729-528596ac-6333-11e8-8f4d-61db397c4dff.jpg)

From Champenois, E. G. 2017, 'Resolving Non-Adiabatic Dynamics in Small Molecules with Few-Femtosecond Sensitivity', PhD Thesis, University of California, Berkeley.

**Comment by stmiguel** [comment]
Thank you! Yeahh.... that was the problem. Would it be possible to have your PhD thesis?  I am very interested on reading it :)

**Comment by stmiguel** [comment]
Dear Elio,

please let me ask you another question: both the fitted image I get and its abel inversion display relatively weak rings that ultimately give rise to oscillations in the photoelectron spectrum (see pic attached). Is there a way to deal with these features?

Thank you!

![pbasex-champenois2](https://user-images.githubusercontent.com/27637366/40732051-bbd36e18-6432-11e8-9867-649acc50d630.png)

**Comment by e-champenois** [comment]
I'm not sure what exactly is causing that, but I'd argue it would be due to data/imaging fidelity. The two clues I see on this figure are (1) the oscillations don't go much below zero, integrating to a net positive number of counts, and (2) there is a left-right asymmetry in your residuals. Two easy things you could try on the pbasex code side of things would be to change the centroid slightly or invert each quadrant independently (using the quadrant_filter option in the foldQuadrant function) and see if these oscillations appear in all of the quadrants or just one. Doing this is also one (non-unique) way to get some idea for error bars on your data. Beyond that, you could look into doing a regularized least squares fit (l2-regularization is implemented in this code already, although l1- might work better to get rid of small spurious features like these oscillations).
It seems your fit is able to get the main two energetic features and some nice angular distributions.

**Comment by stmiguel** [comment]
Hi, Elio,
 
This are the new images I'm getting:
![picture_pbasex](https://user-images.githubusercontent.com/27637366/40976476-9067a06e-68ce-11e8-824d-e0676d85bb07.png)

Instead of using a linear 'k_spacing' Im using the quadratic and this improved my situation. I don't know if I did correctly the inversion by quadrants. In the code, I used quadrant_filters = [1,1,1,1], [1,0,0,0],[0,1,0,0], etc. Is that what you meant? How can I change to l1 regularization?

I symmetrized the input images by averaging over all quadrants. Do you think that there's still room for improvement regarding having a better output spectrum or fitted image (apart from having much better data quality)? 

Thanks!

**Comment by e-champenois** [comment]
Yea, you can try to run quadrant_filter=[1,1,1,1], [1,0,0,0], [0,1,0,0], etc. and see how the results compare.
Besides that, I think it looks good, there isn't any obvious feature in the residual plot (besides the slight asymmetry in the quadrants) that I would worry about.
